### ISSUE TITLE
Add Heuristic for nlightning

### ISSUE THREAD

**Issue by nullcount** [endothermicdev/impscan#2]
New LN implementation just dropped. Can impscan detect them? 

https://github.com/ipms-io/nlightning/blob/main/src/NLightning.Bolts/BOLT9/Features.cs

**Comment by endothermicdev** [comment]
Good idea!  I've added a heuristic matching a mandatory `initial_routing_sync` and optional `var_onion_optin` (feature bits 2 and 9).  I think that's all that's set currently?  That heuristic has priority as well, so it should show up when an nlightning node is announced.  These heuristics are always subject to break as nodes add new features, so let me know or submit a PR if it needs updating please.
